apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: bedriftsoversikt-og-ansatte
  namespace: default
  labels:
    team: teamtag
spec:
  image: navikt/oversikt-over-bedrift-og-ansatte:{{version}}
  team: teamtag
  port: 3000
  ingresses:
    - '{{{ingress}}}'
  liveness:
    path: /bedriftsoversikt-og-ansatte/internal/isAlive
    initialDelay: 5
  readiness:
    path: /bedriftsoversikt-og-ansatte/internal/isReady
    initialDelay: 5
  vault:
    enabled: true
  env:
    - name: APIGW_URL
      value: '{{{api-gw-url}}}'
    - name: LOGIN_URL
      value: '{{{selvbetjening-login-url}}}'