apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: innsyn-AAreg-arbeidsgiver
  namespace: default
  labels:
    team: teamtag
spec:
  image: navikt/oversikt-over-bedrift-og-ansatte:latest
  team: teamtag
  port: 3000
  ingresses:
    - https://arbeidsgiver-q.nav.no/bedriftsoversikt-og-ansatte/
  liveness:
    path: /bedriftsoversikt-og-ansatte/internal/isAlive
    initialDelay: 20
  readiness:
    path: /bedriftsoversikt-og-ansatte/internal/isReady
    initialDelay: 20
  vault:
    enabled: true



